csvfile_params:
  - url_
options:
  - label: 1
    buttonvalue: yes
    shortcut_key: q
  - label: 2
    buttonvalue: no
    shortcut_key: w
  - label: 3
    buttonvalue: maybe
    shortcut_key: e
  - label: 4
    buttonvalue: I don't want to answere
    shortcut_key: r
