UI_text:
  img_alt: Image to compare. Please check URL.
  task_explanation: What do you see in the image?
  pls_download: "Download the CSV File extended with a new '{0}' column."
csvfile_params:
  CSV_delimiter_default: ","
  default_image_URL_Columns:
    - 1
    - 3
  new_column_name: "Answere"

options:
    - buttonvalue: No
      sub_menu_rows: 1
      shortcut_key: x
      row: 0
      color: red

    - label: correct
      buttonvalue: Yes
      color: green
      shortcut_key: y
      row: 0
    - label: Sengon
      buttonvalue: Sengon
      shortcut_key: q
      row: 1
      color: red
    - label: Rasamala
      buttonvalue: Rasamala
      shortcut_key: w
      row: 1
    - label: Manglid
      buttonvalue: Manglid
      shortcut_key: e
      row: 1
    - label: Puspa
      buttonvalue: Puspa
      shortcut_key: r
      row: 1
    - label: Suren
      buttonvalue: Suren
      shortcut_key: t
      row: 1
    - label: Damar
      buttonvalue: Damar
      shortcut_key: z
      row: 1
    - label: Avocado
      buttonvalue: Avocado
      shortcut_key: u
      row: 1
    - label: noTree
      buttonvalue: There is no Tree
      shortcut_key: n
      row: 2

GUI_params:
  default_rows:
    - 0
