UI_text:
  img_alt: Image to compare. Please check URL.
  task_explanation: What do you see in the image?
  pls_download: "Download the CSV File extended with a new '{0}' column."
csvfile_params:
  CSV_delimiter_default: ","
  default_image_URL_Columns:
    - 1
    - 3
  new_column_name: "Answere"
options:
  - label: 1
    buttonvalue: yes
    shortcut_key: q
  - label: 2
    buttonvalue: no
    shortcut_key: w
  - label: 3
    buttonvalue: maybe
    shortcut_key: e
  - label: 4
    buttonvalue: I don't want to answere
    shortcut_key: r
