UI_text:
  img_alt: Image to compare. Please check URL.
  task_explanation: What do you see in the image?
  pls_download: "Download the CSV File extended with a new '{0}' column."
csvfile_params:
  CSV_delimiter_default: ","
  default_image_URL_Columns:
    - 1
    - 3
  new_column_name: "Answere"
options:
  - label: Sengon
    buttonvalue: Sengon
    shortcut_key: q
    row: 1
    color: red
  - label: Rasamala
    buttonvalue: Rasamala
    shortcut_key: w
    row: 1
  - label: Manglid
    buttonvalue: Manglid
    shortcut_key: e
    row: 5
  - label: Puspa
    buttonvalue: Puspa
    shortcut_key: r
  - label: Suren
    buttonvalue: Suren
    shortcut_key: t
  - label: Damar
    buttonvalue: Damar
    shortcut_key: z
  - label: Avocado
    buttonvalue: Avocado
    shortcut_key: u
  - label: ...
    buttonvalue: ...
    shortcut_key: i
